databases:
- name: {{name}}
schemas:
- name: {{schema}}
  database: {{name}}
roles:
- name: {{name}}_rw
privilegeGrants:
- privilege:
    - monitor
    - modify
  objectType: database
  objectName: {{name}}
  roleName: {{name}}_rw
- privilege:
    - create table
    - usage
  objectType: schema
  objectName: {{name}}.{{schema}}
  roleName: {{name}}_rw
