# Managed source and product databases
entries:
  # Sources
  - name: Salesforce
    schema: main
  - name: Hubspot
    schema: main
  - name: Gong
    schema: main
  # Products
  - name: Testco
    schema: main
